#!/bin/bash

# Om Desktop - Publish Release Script
# Publishes a DMG release to om-releases repo with auto-update support

set -e

# Check for gh CLI
if ! command -v gh &> /dev/null; then
  echo "❌ Error: GitHub CLI (gh) is not installed."
  echo "Install it with: brew install gh"
  exit 1
fi

# Verify gh is authenticated
if ! gh auth status &> /dev/null; then
  echo "❌ Error: GitHub CLI is not authenticated."
  echo "Run: gh auth login"
  exit 1
fi

# Get version from package.json
VERSION=$(node -p "require('./package.json').version")
TAG="v$VERSION"

echo "📦 Publishing Om Desktop $TAG to om-releases..."
echo ""

# Check if DMG files exist
ARM64_DMG="dist/Om-$VERSION-arm64.dmg"
X64_DMG="dist/Om-$VERSION-x64.dmg"
UNIVERSAL_DMG="dist/Om-$VERSION.dmg"
LATEST_MAC_YML="dist/latest-mac.yml"

# Try to find the DMG files (electron-builder may use different naming)
if [ ! -f "$ARM64_DMG" ] && [ ! -f "$X64_DMG" ] && [ ! -f "$UNIVERSAL_DMG" ]; then
  # List what's actually in the dist directory
  echo "Looking for DMG files in dist/..."
  ls -la dist/*.dmg 2>/dev/null || true

  echo "❌ Error: DMG build not found"
  echo "Expected one of:"
  echo "   - $ARM64_DMG"
  echo "   - $X64_DMG"
  echo "   - $UNIVERSAL_DMG"
  echo ""
  echo "Run 'npm run build:production' first to build the app."
  exit 1
fi

# Verify latest-mac.yml exists (generated by electron-builder)
if [ ! -f "$LATEST_MAC_YML" ]; then
  echo "❌ Error: latest-mac.yml not found in dist/"
  echo "This file should be generated by electron-builder's zip target."
  echo "Make sure you ran 'npm run build:production' first."
  exit 1
fi

echo "✅ Found builds:"
ls -lh dist/*.dmg 2>/dev/null | awk '{print "   - " $9 " (" $5 ")"}'
echo "   - $LATEST_MAC_YML (auto-update metadata)"
echo ""

# Check if release already exists
if gh release view "$TAG" --repo om-labs/om-releases > /dev/null 2>&1; then
  echo "⚠️  Release $TAG already exists on om-releases."
  read -p "Do you want to delete and recreate it? (y/N) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "🗑️  Deleting existing release..."
    gh release delete "$TAG" --repo om-labs/om-releases --yes
  else
    echo "Aborting."
    exit 1
  fi
fi

# Create release notes
RELEASE_NOTES="## Om Desktop $VERSION

Download the version for your Mac:

- **Apple Silicon** (M1, M2, M3, M4): \`Om-arm64.dmg\`
- **Intel**: \`Om-x64.dmg\`

Not sure which to choose? [Check your Mac's chip](https://support.apple.com/en-us/116943)

### Installation

1. Download the DMG for your Mac's architecture
2. Open the downloaded DMG file
3. Drag the Om app to your Applications folder
4. Launch Om from your Applications folder

### Auto-Updates

This release includes automatic update support. The app will notify you when new versions are available."

echo "📝 Creating release $TAG..."

# Create unversioned copies for stable download URLs
# These allow the marketing site to use /latest/download/Om-arm64.dmg etc.
if [ -f "$ARM64_DMG" ]; then
  cp "$ARM64_DMG" "dist/Om-arm64.dmg"
fi
if [ -f "$X64_DMG" ]; then
  cp "$X64_DMG" "dist/Om-x64.dmg"
fi
if [ -f "$UNIVERSAL_DMG" ]; then
  cp "$UNIVERSAL_DMG" "dist/Om.dmg"
fi

# Upload unversioned DMGs (for manual download), ZIP files (for auto-update), and latest-mac.yml
# Only upload unversioned DMGs to reduce upload size - marketing site uses these stable URLs
gh release create "$TAG" \
  --repo om-labs/om-releases \
  --title "Om Desktop $VERSION" \
  --notes "$RELEASE_NOTES" \
  dist/Om-arm64.dmg \
  dist/Om-x64.dmg \
  dist/*.zip \
  "$LATEST_MAC_YML"

echo ""
echo "✅ Release published successfully!"
echo ""
echo "📥 Download URLs:"
echo "   Latest: https://github.com/om-labs/om-releases/releases/latest"
echo ""
echo "🔗 Release page: https://github.com/om-labs/om-releases/releases/tag/$TAG"
echo ""
echo "🔄 Auto-updates: Enabled via latest-mac.yml"
