-- Add general_overview column to meeting_analysis table
-- This stores a 1-sentence description of the meeting's purpose and type
-- Generated by LLM analysis after pillar scores are calculated

ALTER TABLE public.meeting_analysis
ADD COLUMN IF NOT EXISTS general_overview text;

-- Add comment explaining the column
COMMENT ON COLUMN public.meeting_analysis.general_overview IS 'AI-generated one-sentence overview describing the meeting type and purpose (e.g., "A brainstorming session for Q4 roadmap planning")';
